import ROOT as r
#r.gSystem.Load("libMyTreeReader")
ts = r.TStopwatch()
ts.Start()
r.gROOT.LoadMacro("helpers.cc+")
#r.MCMatch.genMultipleMatch("../Lists/20210217/Merged_PA8TeV_Pbp_LamCKsP0p9_pT0p9to6p1_y1p1_MC_Training_20210217.list")
#r.MCMatch.genMultipleMatch("../Lists/20210217/Merged_PA8TeV_pPb_LamCKsP0p9_pT0p9to6p1_y1p1_MC_Training_20210217.list")
#r.MCMatch.genLcMultipleMatch("../../../pPb.list")
#r.MCMatch.genKsMultipleMatch("../../../pPb.list", 0.03, 0.1)
#r.MCMatch.genKsSingleMatch("../../../pPb.list", 0.03, 0.1)
#r.MCMatch.genKsMultipleMatch("../../../pPb.list")
#r.MCMatch.genKsSingleMatch("../../../pPb.list")
#r.MCMatch.genStableKsMultipleMatch("../../../ks_pPb.list")
#r.MCMatch.genKsMass('../../../ks_pPb.list', 'ksAna_mc', 20000)
#r.MCMatch.genKsMass('../../../pPb.list', 'ksAna_mc', 20000)
#r.MCMatch.genKsMass('../../../pPb.list', 'lambdacAna_mc', 20000)
#r.MCMatch.genLamMass('xi.list', 'LambdaAna_mc', 878682)
#r.MCMatch.genLamMass('xi.list', 'LambdaAna_mc', 878682)
r.MCMatch.genLamInXiMass('xi.list', 'XiAna_mc', 2878682)
ts.Stop()
ts.Print()
